restaurantApp/restaurant/urls.py
from django.urls import path
from .  import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('index/', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('menu/', views.MenuListClassView.as_view(), name='menu'),
    path('order/', views.OrderClassView.as_view(), name='order'),
    path('cart/', views.view_cart, name='view_cart'),
    path('add/<int:menu_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

restaurantApp/restaurant/models.py
from django.db import models
from django.contrib.auth.models import User
from image_cropping import ImageRatioField

# Create your models here.

STATUS = (
    (0, "Unavailable"),
    (1 , "Available")
)

class MenuType(models.Model):
    menu_type = models.CharField(max_length=100, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUS, default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name ='menu_type'
        verbose_name_plural ='menu_types'

    def __str__(self):
        return self.menu_type

class MenuItem(models.Model):
    menu_item = models.CharField(max_length=100)
    menu_type = models.ForeignKey(MenuType, on_delete=models.SET_NULL, null=True)
    description = models.CharField(max_length=2000)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    menu_image = models.ImageField(upload_to="menu_image/")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUS, default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)


    class Meta:
        verbose_name = 'menu_item'
        verbose_name_plural = 'menu_items'

    def __str__(self):
        return self.menu_item


class MenuImage(models.Model):
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    menu_image = models.ImageField(upload_to="menu_image/", blank=True, null=False)
    cropping = ImageRatioField('menu_image', '400x400')
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.menu_item.menu_item} - {self.menu_image}"


class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.menu_item.menu_item} - {self.quantity}"

restaurantApp/restaurant/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import MenuItem, MenuType, CartItem
from django.views.generic import ListView, TemplateView

# Create your views here.
# def MenuList(request):
#     menu_items = MenuItem.objects.all()
#     menu_types = MenuType.objects.all()
#     template_name = "menu.html"
#     context = {
#         "menu_items": menu_items,
#         "menu_types": menu_types,
#         }
#     return render(request, template_name, context)

class HomeView(TemplateView):
    template_name = 'index.html'

class AboutView(TemplateView):
    template_name = "about.html"

class MenuListClassView(ListView):
    model = MenuItem
    template_name = "menu.html"
    context_object_name = 'menu_items'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu_types'] = MenuType.objects.all()
        return context

class OrderClassView(ListView):
    model = MenuItem
    template_name = "order.html"
    context_object_name = 'menu_items'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu_types'] = MenuType.objects.all()
        return context

def view_cart(request):
    cart_items = CartItem.objects.filter(user=request.user)
    total_price = sum(item.menu_item.price * item.quantity for item in cart_items)
    return render(request, "view_cart.html", {'cart_items': cart_items, 'total_price': total_price})

def add_to_cart(request, menu_id):
    menu_item = MenuItem.object.get(id=menu_id)
    cart_item, created = CartItem.objects.get_or_create(menu_item=menu_item, user=request.user)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('restaurant:view_cart')

def remove_from_cart(request, item_id):
    cart_item = CartItem.objects.get(id=item_id)
    cart_item.delete()
    return redirect('restaurant:view_cart')

restaurantApp/restaurant/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- About Section -->
<section id="about" class="about section">

    <!-- Section Title -->
    <div class="container section-title" data-aos="fade-up">
      <!-- <h2>About Us<br></h2> -->
      <p><span>Learn More</span> <span class="description-title">About Us</span></p>
    </div><!-- End Section Title -->

    <div class="container">

      <div class="row gy-4">
        <div class="col-lg-7" data-aos="fade-up" data-aos-delay="100">
          <img src="assets/img/about.jpg" class="img-fluid mb-4" alt="">
          <div class="book-a-table">
            <h3>Book a Table</h3>
            <p>+1 5589 55488 55</p>
          </div>
        </div>
        <div class="col-lg-5" data-aos="fade-up" data-aos-delay="250">
          <div class="content ps-0 ps-lg-5">
            <p class="fst-italic">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua.
            </p>
            <ul>
              <li><i class="bi bi-check-circle-fill"></i> <span>Ullamco laboris nisi ut aliquip ex ea commodo consequat.</span></li>
              <li><i class="bi bi-check-circle-fill"></i> <span>Duis aute irure dolor in reprehenderit in voluptate velit.</span></li>
              <li><i class="bi bi-check-circle-fill"></i> <span>Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</span></li>
            </ul>
            <p>
              Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
              velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident
            </p>

            <div class="position-relative mt-4">
              <img src="{% static 'images/about-2.jpg' %}" class="img-fluid" alt="">
              <a href="https://www.youtube.com/watch?v=Y7f98aduVJ8" class="glightbox pulsating-play-btn"></a>
            </div>
          </div>
        </div>
      </div>

    </div>

  </section><!-- /About Section -->
  <!-- Why Us Section -->
  <section id="why-us" class="why-us section light-background">

    <div class="container">

      <div class="row gy-4">

        <div class="col-lg-4" data-aos="fade-up" data-aos-delay="100">
          <div class="why-box">
            <h3>Why Choose Yummy</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis aute irure dolor in reprehenderit
              Asperiores dolores sed et. Tenetur quia eos. Autem tempore quibusdam vel necessitatibus optio ad corporis.
            </p>
            <div class="text-center">
              <a href="#" class="more-btn"><span>Learn More</span> <i class="bi bi-chevron-right"></i></a>
            </div>
          </div>
        </div><!-- End Why Box -->

        <div class="col-lg-8 d-flex align-items-stretch">
          <div class="row gy-4" data-aos="fade-up" data-aos-delay="200">

            <div class="col-xl-4">
              <div class="icon-box d-flex flex-column justify-content-center align-items-center">
                <i class="bi bi-clipboard-data"></i>
                <h4>Corporis voluptates officia eiusmod</h4>
                <p>Consequuntur sunt aut quasi enim aliquam quae harum pariatur laboris nisi ut aliquip</p>
              </div>
            </div><!-- End Icon Box -->

            <div class="col-xl-4" data-aos="fade-up" data-aos-delay="300">
              <div class="icon-box d-flex flex-column justify-content-center align-items-center">
                <i class="bi bi-gem"></i>
                <h4>Ullamco laboris ladore lore pan</h4>
                <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt</p>
              </div>
            </div><!-- End Icon Box -->

            <div class="col-xl-4" data-aos="fade-up" data-aos-delay="400">
              <div class="icon-box d-flex flex-column justify-content-center align-items-center">
                <i class="bi bi-inboxes"></i>
                <h4>Labore consequatur incidid dolore</h4>
                <p>Aut suscipit aut cum nemo deleniti aut omnis. Doloribus ut maiores omnis facere</p>
              </div>
            </div><!-- End Icon Box -->

          </div>
        </div>

      </div>

    </div>

  </section><!-- /Why Us Section -->

{% endblock %}

restaurantApp/restaurant/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Starter Page - Yummy Bootstrap Template</title>
  <meta name="description" content="">
  <meta name="keywords" content="">

  <!-- Favicons -->
  <link href="{% static 'css/main.css' %}" href="assets/img/favicon.png" rel="icon">
  <link href="{% static 'css/main.css' %}" href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Amatic+SC:wght@400;700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}"  rel="stylesheet">
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'css/main.css' %}" rel="stylesheet">
  {%  block extra_css %}
  {%  endblock extra_css %}

</head>
    <body class="starter-page-page">
      <header id="header" class="header d-flex align-items-center sticky-top">
        <div class="container position-relative d-flex align-items-center justify-content-between">

          <a href="{% url 'restaurant:home' %}" class="logo d-flex align-items-center me-auto me-xl-0">
            <!-- Uncomment the line below if you also wish to use an image logo -->
            <!-- <img src="{% static 'images/logo.png' %}" alt=""> -->
            <h1 class="sitename">Your Restaurant</h1>
            <span>.</span>
          </a>

          <nav id="navmenu" class="navmenu">
            <ul>
              <li><a href="{% url 'restaurant:home' %}">Home<br></a></li>
              <li><a href="{% url 'restaurant:about' %}">About</a></li>
              <li><a href="{% url 'restaurant:menu' %}">Menu</a></li>
              <li><a href="{% url 'restaurant:home' %}">Contact</a></li>
            </ul>
            <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
          </nav>

          <a class="btn-getstarted" href="{% url 'restaurant:order' %}">Place a Order</a>

        </div>
      </header>
      <main class=""main>
        {% block content %}
        {% endblock %}
      </main>
        <div class="container">

        </div>

        <footer id="footer" class="footer dark-background">

    <div class="container">
      <div class="row gy-3">
        <div class="col-lg-3 col-md-6 d-flex">
          <i class="bi bi-geo-alt icon"></i>
          <div class="address">
            <h4>Address</h4>
            <p>A108 Adam Street</p>
            <p>Miami, FL 535022</p>
            <p></p>
          </div>

        </div>

        <div class="col-lg-3 col-md-6 d-flex">
          <i class="bi bi-telephone icon"></i>
          <div>
            <h4>Contact</h4>
            <p>
              <strong>Phone:</strong> <span>+1 5589 55488 55</span><br>
              <strong>Email:</strong> <span>info@example.com</span><br>
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 d-flex">
          <i class="bi bi-clock icon"></i>
          <div>
            <h4>Opening Hours</h4>
            <p>
              <strong>Mon-Sat:</strong> <span>11AM - 23PM</span><br>
              <strong>Sunday</strong>: <span>Closed</span>
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6">
          <h4>Follow Us</h4>
          <div class="social-links d-flex">
            <a href="#" class="twitter"><i class="bi bi-twitter-x"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

      </div>
    </div>

    <div class="container copyright text-center mt-4">
      <p>© <span>Copyright</span> <strong class="px-1 sitename">Restaurant</strong> <span>All Rights Reserved</span></p>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you've purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
        <!-- Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> -->
      </div>
    </div>

  </footer>

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <!-- <script src="assets/vendor/php-email-form/validate.js"></script> -->
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}" ></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}" ></script>

  <!-- Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

  {%  block extra_js %}
  {%  endblock extra_js %}
    </body>
</html>

restaurantApp/restaurant/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section id="hero" class="hero section light-background">

    <div class="container">
      <div class="row gy-4 justify-content-center justify-content-lg-between">
        <div class="col-lg-5 order-2 order-lg-1 d-flex flex-column justify-content-center">
          <h1 data-aos="fade-up">Enjoy Your Healthy<br>Delicious Food</h1>
          <p data-aos="fade-up" data-aos-delay="100">We are team of talented designers making websites with Bootstrap</p>
          <div class="d-flex" data-aos="fade-up" data-aos-delay="200">
            <a href="{% url 'restaurant:order' %}" class="btn-get-started">Order Now</a>
            <a href="#" class="glightbox btn-watch-video d-flex align-items-center"><i class="bi bi-play-circle"></i><span>Watch Video</span></a>
          </div>
        </div>
        <div class="col-lg-5 order-1 order-lg-2 hero-img" data-aos="zoom-out">
          <img src="{% static 'images/hero-img.png' %}" class="img-fluid animated" alt="">
        </div>
      </div>
    </div>

  </section>
<div class="container">
{% endblock %}

restaurantApp/restaurant/templates/menu.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Menu Section -->
<section id="menu" class="menu section">

  <!-- Section Title -->
  <div class="container section-title" data-aos="fade-up">
    <h2>Our Menu</h2>
    <p><span>Check Our</span> <span class="description-title">Yummy Menu</span></p>
  </div><!-- End Section Title -->

  <div class="container">

    <div class="nav nav-tabs d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100">
      {%  for category in menu_types %}
      <div class="nav-item">
        <button class="nav-link" data-id="menu-{{ category }}" data-bs-toggle="tab" data-bs-target="#menu-{{ category }}">
          {{ category | capfirst}}
        </button>
      </div><!-- End tab nav item -->
      {% endfor %}
    </div>

    <div class="tab-content" data-aos="fade-up" data-aos-delay="200">
      {%  for category in menu_types %}
      <div class="tab-pane fade" id="menu-{{ category }}">
        <div class="tab-header text-center">
          <p>Menu</p>
          <h3>{{ category | capfirst}}</h3>
        </div>
        <div class="row gy-5">
          {% for menu_item in menu_items %}
          {%  if menu_item.menu_type == category %}
          <div class="col-lg-4 menu-item">
            <img src="/media/{{ menu_item.menu_image }}" class="menu-img img-fluid" alt="">
            <h4>{{ menu_item.menu_item }}</h4>
            <p class="ingredients">
              {{ menu_item.description }}
            </p>
            <p class="price">
              ${{ menu_item.price }}
            </p>
          </div><!-- Menu Item -->
          {%  endif %}
          {%  endfor %}
        </div>
      </div><!-- End Starter Menu Content -->
      {%  endfor %}
    </div>

  </div>

</section><!-- /Menu Section -->

{% endblock %}
{%  block extra_js %}
<script src="{% static 'js/home.js' %}"></script>
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->
{%  endblock extra_js %}

restaurantApp/restaurant/templates/menu_item_details.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ item.meal }}</h1>
    <p>{{ item.description }}</p>
    <p>{{ item.price }}</p>
{% endblock %}

restaurantApp/restaurant/templates/order.html
{% extends 'base.html' %}
{% load static %}
{%  block extra_css %}
  <link rel="stylesheet" href="{% static 'css/order.css' %}">
{%  endblock extra_css %}
{% block content %}
<section id="order" class="menu section">
    <!-- Order Title -->
    <div class="container section-title">
        <h2>Order Here</h2>
        <p><span>Check Our</span> <span class="description-title">Yummy Menu</span></p>
    </div><!-- End Order Title -->

    <div class="container">
      <div class="nav nav-tabs d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100">
        {%  for category in menu_types %}
        <div class="nav-item">
          <button class="nav-link" data-id="menu-{{ category }}" data-bs-toggle="tab" data-bs-target="#menu-{{ category }}">
            {{ category | capfirst}}
          </button>
        </div><!-- End tab nav item -->
        {% endfor %}
      </div>
      <div class="tab-content" data-aos="fade-up" data-aos-delay="200">
        <div class="tab-pane fade active show" id="menu-starters">
          <div class="tab-header text-center">
            <p>Menu</p>
            <h3>Starters</h3>
          </div>
          <div class="gy-5">

            <div class="order-item">
              <!-- <img src="assets/img/menu/menu-item-1.png" alt=""></a> -->
              <div class="item-name">
                <h4>Magnam Tiste</h4>
              </div>
              <div class="description">
                <p class="ingredients">
                  Lorem, deren, trataro, filede, nerada
                </p>
              </div>
              <div class="price">
                <p class="price">
                  $5.95
                </p>
              </div>
              <div class="quantity">
                <button class="plus-btn" type="button" name="button">
                  +
                </button>
                <input type="text" name="name" value="1">
                <button class="minus-btn" type="button" name="button">
                  -
                </button>
              </div>
            </div><!-- Menu Item -->
          </div>
        </div><!-- End Starter Menu Content -->

      </div>
    </div>

</section>

<div class="shopping-cart">
  <!-- Title -->
  <div class="title">
    Shopping Bag
  </div>

  <!-- Product #1 -->
  <div class="item">
    <div class="buttons">
      <span class="delete-btn"></span>
      <span class="like-btn"></span>
    </div>

    <div class="image">
      <!-- <img src="item-1.png" alt="" /> -->
    </div>

    <div class="description">
      <span>Common Projects</span>
      <span>Bball High</span>
      <span>White</span>
    </div>

    <div class="quantity">
      <button class="plus-btn" type="button" name="button">
        +
      </button>
      <input type="text" name="name" value="1">
      <button class="minus-btn" type="button" name="button">
        -
      </button>
    </div>

    <div class="total-price">$549</div>
  </div>

  <!-- Product #2 -->
  <div class="item">
    <div class="buttons">
      <span class="delete-btn"></span>
      <span class="like-btn"></span>
    </div>

    <div class="image">
      <!-- <img src="item-2.png" alt="" /> -->
    </div>

    <div class="description">
      <span>Maison Margiela</span>
      <span>Future Sneakers</span>
      <span>White</span>
    </div>

    <div class="quantity">
      <button class="plus-btn" type="button" name="button">
        +
      </button>
      <input type="text" name="name" value="1">
      <button class="minus-btn" type="button" name="button">
        -
      </button>
    </div>

    <div class="total-price">$870</div>
  </div>

  <!-- Product #3 -->
  <div class="item">
    <div class="buttons">
      <span class="delete-btn"></span>
      <span class="like-btn"></span>
    </div>

    <div class="image">
      <!-- <img src="item-3.png" alt="" /> -->
    </div>

    <div class="description">
      <span>Our Legacy</span>
      <span>Brushed Scarf</span>
      <span>Brown</span>
    </div>

    <div class="quantity">
      <button class="plus-btn" type="button" name="button">
        +
      </button>
      <input type="text" name="name" value="1">
      <button class="minus-btn" type="button" name="button">
        -
      </button>
    </div>

    <div class="total-price">$349</div>
  </div>
</div>

{% endblock %}
{%  block extra_js %}
<script src="{% static 'js/order.js' %}"></script>
{%  endblock extra_js %}

restaurantApp/restaurant/templates/view_cart.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        /* Add CSS styles for flex container and items */
        .product-list {
            display: flex;
            flex-wrap: wrap; /* Allow items to wrap to the next row if necessary */
            justify-content: space-between; /* Space items evenly along the main axis */
            list-style: none; /* Remove list styles */
            padding: 0;
        }

        .product-item {

            flex: 1; /* Grow to fill available space evenly */
             /* Limit item width to avoid overcrowding */
            margin: 10px; /* Add spacing between items */
            border: 1px solid #ccc; /* Add a border for visual separation */
            padding: 10px;
            text-align: center;
        }

        /* Style the "Buy Now" button */
        .buy-now-button {
            display: block;
            margin-top: 10px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            padding: 5px 10px;
            border-radius: 5px;
        }
    </style>
</head>

<body>

    <h1>Shopping Cart</h1>

<div class="shopping-cart">

  <div class="column-labels">
    <label class="product-image">Image</label>
    <label class="product-details">Product</label>
    <label class="product-price">Price</label>
    <label class="product-quantity">Quantity</label>
    <label class="product-removal">Remove</label>
    <label class="product-line-price">Total</label>
  </div>

  <div class="product">
    <div class="product-image">
      <img src="https://s.cdpn.io/3/dingo-dog-bones.jpg">
    </div>
    <div class="product-details">
      <div class="product-title">Dingo Dog Bones</div>
      <p class="product-description">The best dog bones of all time. Holy crap. Your dog will be begging for these things! I got curious once and ate one myself. I'm a fan.</p>
    </div>
    <div class="product-price">12.99</div>
    <div class="product-quantity">
      <input type="number" value="2" min="1">
    </div>
    <div class="product-removal">
      <button class="remove-product">
        Remove
      </button>
    </div>
    <div class="product-line-price">25.98</div>
  </div>

  <div class="product">
    <div class="product-image">
      <img src="https://s.cdpn.io/3/large-NutroNaturalChoiceAdultLambMealandRiceDryDogFood.png">
    </div>
    <div class="product-details">
      <div class="product-title">Nutro™ Adult Lamb and Rice Dog Food</div>
      <p class="product-description">Who doesn't like lamb and rice? We've all hit the halal cart at 3am while quasi-blackout after a night of binge drinking in Manhattan. Now it's your dog's turn!</p>
    </div>
    <div class="product-price">45.99</div>
    <div class="product-quantity">
      <input type="number" value="1" min="1">
    </div>
    <div class="product-removal">
      <button class="remove-product">
        Remove
      </button>
    </div>
    <div class="product-line-price">45.99</div>
  </div>

  <div class="totals">
    <div class="totals-item">
      <label>Subtotal</label>
      <div class="totals-value" id="cart-subtotal">71.97</div>
    </div>
    <div class="totals-item">
      <label>Tax (5%)</label>
      <div class="totals-value" id="cart-tax">3.60</div>
    </div>
    <div class="totals-item">
      <label>Shipping</label>
      <div class="totals-value" id="cart-shipping">15.00</div>
    </div>
    <div class="totals-item totals-item-total">
      <label>Grand Total</label>
      <div class="totals-value" id="cart-total">90.57</div>
    </div>
  </div>

      <button class="checkout">Checkout</button>

</div>



</body>

</html>